select ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
from ANIMAL_OUTS
left join ANIMAL_INS
on ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID 
where ANIMAL_INS.ANIMAL_ID IS NULL
order by ANIMAL_OUTS.ANIMAL_ID


# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_OUTS O
# LEFT JOIN ANIMAL_INS I
# ON O.ANIMAL_ID = I.ANIMAL_ID
# WHERE I.ANIMAL_ID IS NULL
# ORDER BY O.ANIMAL_ID;